import { describe, it, expect } from 'vitest';
import { exportScenarioToICS, getGoogleCalendarLink, getOutlookCalendarLink, icsPeriodForRange } from '../icsExport';
import { Scenario } from '../../types';
import { en } from '../../i18n/locales/en';

const testScenario: Scenario = {
    id: 'ics-test',
    name: 'Teste ICS',
    teams: 1,
    shiftDuration: 8,
    weeklyHoursContract: 40,
    pattern: 'MMTTNNFFFF',
};

describe('icsExport', () => {
    describe('exportScenarioToICS', () => {
        it('should return a valid ICS string', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('BEGIN:VCALENDAR');
            expect(ics).toContain('END:VCALENDAR');
        });

        it('should include VERSION 2.0', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('VERSION:2.0');
        });

        it('should include PRODID', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('PRODID:-//ShiftSim Factory//Schedule Generator//EN');
        });

        it('should include scenario name in X-WR-CALNAME', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('X-WR-CALNAME:Teste ICS');
        });

        it('should contain VEVENT blocks', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('BEGIN:VEVENT');
            expect(ics).toContain('END:VEVENT');
        });

        it('should include VALARM for reminders', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('BEGIN:VALARM');
            expect(ics).toContain('END:VALARM');
        });

        it('should use CRLF line endings', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            expect(ics).toContain('\r\n');
        });

        it('should generate unique UIDs per event', () => {
            const ics = exportScenarioToICS(testScenario, 2025);
            const uidMatches = ics.match(/UID:(.+)/g);
            if (uidMatches) {
                const uids = uidMatches.map(u => u.replace('UID:', ''));
                const uniqueUids = new Set(uids);
                expect(uniqueUids.size).toBe(uids.length);
            }
        });

        it('should include team name in event summaries', () => {
            const ics = exportScenarioToICS(testScenario, 2025, 0);
            expect(ics).toContain('Equipa A');
        });

        it('should generate for specific team when teamIndex provided', () => {
            const multiTeam: Scenario = { ...testScenario, teams: 3 };
            const ics = exportScenarioToICS(multiTeam, 2025, 1);
            expect(ics).toContain('Equipa B');
        });

        it('should generate for all teams when teamIndex not provided', () => {
            const multiTeam: Scenario = { ...testScenario, teams: 2 };
            const ics = exportScenarioToICS(multiTeam, 2025);
            expect(ics).toContain('Equipa A');
            expect(ics).toContain('Equipa B');
        });

        it('should include shift type in descriptions (default pt)', () => {
            const ics = exportScenarioToICS(testScenario, 2025, 0);
            expect(ics).toMatch(/DESCRIPTION:.*Manha/);
            expect(ics).toMatch(/DESCRIPTION:.*Equipa A/);
        });

        it('should localize shift and team names when a translations object is provided', () => {
            const ics = exportScenarioToICS(testScenario, 2025, 0, en);
            expect(ics).toContain('Morning');
            expect(ics).toContain('Team A');
            expect(ics).not.toContain('Manha');
            expect(ics).not.toContain('Equipa');
        });

        it('should fall back to pt when no translations are provided', () => {
            const ics = exportScenarioToICS(testScenario, 2025, 0);
            expect(ics).toContain('Manha');
            expect(ics).toContain('Equipa A');
        });

        it('should localize X-WR-CALDESC when a translations object is provided', () => {
            const ics = exportScenarioToICS(testScenario, 2025, undefined, en);
            expect(ics).toContain('X-WR-CALDESC:Schedule generated by ShiftSim Factory — 1 teams, 8h shifts');
            expect(ics).not.toContain('Horario gerado pelo ShiftSim Factory');
        });

        it('should localize X-WR-CALDESC in pt by default', () => {
            const ics = exportScenarioToICS(testScenario, 2025, undefined);
            expect(ics).toContain('X-WR-CALDESC:Horario gerado pelo ShiftSim Factory — 1 equipas, turnos de 8h');
        });

        it('should include CATEGORIES', () => {
            const ics = exportScenarioToICS(testScenario, 2025, 0);
            expect(ics).toContain('CATEGORIES:');
        });
    });

    describe('getGoogleCalendarLink', () => {
        it('should return a Google Calendar URL', () => {
            const link = getGoogleCalendarLink(testScenario, 2025);
            expect(link).toContain('https://calendar.google.com/calendar/render');
        });

        it('should include cid parameter', () => {
            const link = getGoogleCalendarLink(testScenario, 2025);
            expect(link).toContain('cid=');
        });
    });

    describe('getOutlookCalendarLink', () => {
        it('should return an Outlook Calendar URL', () => {
            const link = getOutlookCalendarLink(testScenario, 2025);
            expect(link).toContain('https://outlook.office.com/calendar/addcalendar');
        });

        it('should include url parameter', () => {
            const link = getOutlookCalendarLink(testScenario, 2025);
            expect(link).toContain('url=');
        });
    });

    describe('period filtering', () => {
        const countEvents = (ics: string) => (ics.match(/BEGIN:VEVENT/g) || []).length;

        it('should include icsPeriodForRange helper returning undefined for full year', () => {
            expect(icsPeriodForRange('full', 2025)).toBeUndefined();
        });

        it('should return a valid period for a quarter', () => {
            const p = icsPeriodForRange('q1', 2025);
            expect(p).toBeDefined();
            expect(p!.start.getMonth()).toBe(0);
            expect(p!.end.getMonth()).toBe(2);
        });

        it('should export a subset of events when a period is provided', () => {
            const full = exportScenarioToICS(testScenario, 2025);
            const q1 = exportScenarioToICS(testScenario, 2025, undefined, undefined, icsPeriodForRange('q1', 2025));
            expect(countEvents(q1)).toBeGreaterThan(0);
            expect(countEvents(q1)).toBeLessThan(countEvents(full));
        });

        it('should only contain events within the chosen period', () => {
            const q1 = exportScenarioToICS(testScenario, 2025, undefined, undefined, icsPeriodForRange('q1', 2025));
            const uidMatches = q1.match(/UID:(.+)/g) || [];
            expect(uidMatches.length).toBe(countEvents(q1));
            expect(q1).toContain('BEGIN:VEVENT');
            expect(q1).toContain('END:VEVENT');
        });
    });
});
